language: node_js
deploy:
  api_key:
    secure: QtskoIWJs7H7ubU+p4qbJ7eeYP4EJoFaf4yJEKnWpV63kgEitKDuRAegh2/6YdpCAsVZ3k7XFs0g8/TcO3HzpUqhe5WWVbX3H5gdLSk570ZLa4z9Jxr/e40crICRQwnN9fDePpUrwAYYCKObnKyDXXVJsw8nAPgmMLgTob67WQM=
  provider: npm
  email: john@mclear.co.uk
